const DAYS=[['2026-10-21','بنغازي → تونس → روما'],['2026-10-22','روما'],['2026-10-23','روما'],['2026-10-24','روما → برشلونة'],['2026-10-25','برشلونة → نيس'],['2026-10-26','Nice • Èze • Monaco'],['2026-10-27','Nice → Portofino'],['2026-10-28','Portofino → Lake Como'],['2026-10-29','Lake Como'],['2026-10-30','Como → Milan'],['2026-10-31','Milan Derby'],['2026-11-01','Milan → Lucerne'],['2026-11-02','Lucerne → Interlaken'],['2026-11-03','Jungfraujoch'],['2026-11-04','Interlaken → Geneva'],['2026-11-05','Geneva → Benghazi']];
const K='europe26-state-v2';let S=JSON.parse(localStorage.getItem(K)||'null')||{done:[],profile:{},bookings:[{id:'derby',date:'2026-10-31',type:'تذكرة/معلم',name:'Milan vs Inter — San Siro',time:'20:45',price:'449',currency:'EUR',status:'مدفوع ومؤكد',confirm:'',ticket:'',lat:'',lon:'',radius:'500',notes:'Gate 15 • Sector X • Row 12 • Seat 12'}]};
const $=id=>document.getElementById(id);function save(){localStorage.setItem(K,JSON.stringify(S));render()};function esc(x){return String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function current(){return DAYS.find(d=>!S.done.includes(d[0]))||DAYS[DAYS.length-1]}
function render(){let c=current();$('headline').textContent='16 يومًا • كل حجز وخطوة في مكان واحد';$('nextTitle').textContent=c[1];$('nextText').textContent=c[0]+' — عند وصولك لنقطة محفوظة يمكن للتطبيق التحقق من الموقع بإذنك.';$('summary').innerHTML=S.bookings.filter(b=>b.status==='مدفوع ومؤكد').map(b=>`<div class='booking'><b>${esc(b.name)}</b><br><span class='muted'>${esc(b.date)} ${esc(b.time)} • ${esc(b.price)} ${esc(b.currency)}</span></div>`).join('')||'<p class="muted">لا توجد حجوزات مؤكدة بعد.</p>';$('days').innerHTML=DAYS.map((d,i)=>{let done=S.done.includes(d[0]),cur=d[0]===c[0];let bs=S.bookings.filter(b=>b.date===d[0]);return `<div class='card day ${done?'done':cur?'current':''}'><b>${i+1}. ${esc(d[1])}</b><div class='muted'>${d[0]} ${done?'• ✓ منجز':cur?'• المرحلة الحالية':''}</div>${bs.map(b=>`<div class='booking'>${esc(b.name)} <span class='pill'>${esc(b.status)}</span></div>`).join('')}<button class='soft daydone' data-date='${d[0]}'>${done?'إلغاء الإنجاز':'✓ تم الوصول/الإنجاز'}</button></div>`}).join('');$('bookingList').innerHTML=S.bookings.map(b=>`<div class='card'><b>${esc(b.name)}</b><div class='muted'>${esc(b.date)} • ${esc(b.type)} • ${esc(b.status)}</div><div>${b.price?esc(b.price)+' '+esc(b.currency):''}</div><button class='soft edit' data-id='${b.id}'>تعديل</button>${b.ticket?`<a href='${esc(b.ticket)}' target='_blank'><button type='button'>فتح التذكرة</button></a>`:''}</div>`).join('');document.querySelectorAll('.daydone').forEach(b=>b.onclick=()=>{let d=b.dataset.date;S.done=S.done.includes(d)?S.done.filter(x=>x!==d):[...S.done,d];save()});document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openEdit(b.dataset.id))}
function view(v){document.querySelectorAll('main section').forEach(s=>s.classList.add('hide'));$(v).classList.remove('hide')}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.v));
$('date').innerHTML=DAYS.map(d=>`<option value='${d[0]}'>${d[0]} — ${d[1]}</option>`).join('');$('addBooking').onclick=()=>{ $('bookingForm').reset();$('editId').value='';$('radius').value='500';$('dlg').showModal()};$('cancel').onclick=()=>$('dlg').close();
function openEdit(id){let b=S.bookings.find(x=>x.id===id);if(!b)return;['date','type','name','time','price','currency','status','confirm','ticket','lat','lon','radius','notes'].forEach(k=>$(k==='name'?'bname':k).value=b[k]||'');$('editId').value=id;$('dlg').showModal()}
$('bookingForm').onsubmit=e=>{e.preventDefault();let id=$('editId').value||crypto.randomUUID();let b={id,date:$('date').value,type:$('type').value,name:$('bname').value.trim(),time:$('time').value.trim(),price:$('price').value.trim(),currency:$('currency').value,status:$('status').value,confirm:$('confirm').value.trim(),ticket:$('ticket').value.trim(),lat:$('lat').value.trim(),lon:$('lon').value.trim(),radius:$('radius').value.trim()||'500',notes:$('notes').value.trim()};let i=S.bookings.findIndex(x=>x.id===id);i<0?S.bookings.push(b):S.bookings[i]=b;$('dlg').close();save()};
$('manualDone').onclick=()=>{let c=current();if(!S.done.includes(c[0])){S.done.push(c[0]);save()}};
function dist(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,A=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))}
$('locate').onclick=()=>{if(!navigator.geolocation){$('locmsg').textContent='الموقع غير مدعوم في هذا المتصفح.';return}$('locmsg').textContent='جاري التحقق من الموقع…';navigator.geolocation.getCurrentPosition(pos=>{let candidates=S.bookings.filter(b=>b.lat&&b.lon&&!S.done.includes(b.date));if(!candidates.length){$('locmsg').textContent='لا توجد نقطة GPS محفوظة للمرحلة التالية. أضف إحداثيات الفندق/المطار/المعلم في الحجز.';return}let nearest=candidates.map(b=>[b,dist(pos.coords.latitude,pos.coords.longitude,+b.lat,+b.lon)]).sort((x,y)=>x[1]-y[1])[0];let [b,m]=nearest;if(m<=+(b.radius||500)){$('locmsg').innerHTML=`<span class='ok'>✓ أنت داخل نطاق ${esc(b.name)} — ${Math.round(m)} م.</span>`;if(!S.done.includes(b.date)){S.done.push(b.date);save()}}else $('locmsg').innerHTML=`<span class='warn'>أقرب نقطة: ${esc(b.name)} — تبعد تقريبًا ${(m/1000).toFixed(1)} كم.</span>`},err=>$('locmsg').textContent='لم أحصل على الموقع. فعّل صلاحية الموقع للتطبيق ثم حاول مجددًا.',{enableHighAccuracy:true,timeout:12000,maximumAge:30000})};
$('saveProfile').onclick=()=>{S.profile={name:$('name').value,phone:$('phone').value,email:$('email').value,passport:$('passport').value,emergency:$('emergency').value};save();alert('تم الحفظ محليًا')};function loadp(){let p=S.profile||{};['name','phone','email','passport','emergency'].forEach(k=>$(k).value=p[k]||'')}loadp();
$('exportBtn').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='Europe2026-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.bookings)throw 0;S=x;save();loadp()}catch{alert('ملف غير صالح')}};r.readAsText(f)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
